### ISSUE TITLE
Remove use of patchwork from vignette

### ISSUE THREAD

**Issue by lwjohnst86** [moderndive/moderndive#111]
Part of the JOSE review https://github.com/openjournals/jose-reviews/issues/115

Related to #105, in order to automatically build the website, the patchwork package is required for building the vignette. Since it is only needed for that, I'd suggest removing its use so you can remove the `Suggests` dependency for patchwork.

**Comment by rudeboybert** [comment]
Thanks for the suggestion. However we really want [Figures 7 & 8](https://raw.githubusercontent.com/openjournals/jose-papers/jose.00115/jose.00115/10.21105.jose.00115.pdf) to be presented side-by-side so that the reader can make quick comparisons.
