### ISSUE TITLE
issue with upcoming broom release

### ISSUE THREAD

**Issue by simonpcouch** [moderndive/moderndive#128]
Hey yall!

I'm prepping a broom release at the moment and am seeing new issues with your package in reverse dependency checks:

```
Changes to worse in reverse depends:

Package: moderndive
Check: tests
New result: ERROR
    Running ‘testthat.R’ [6s/6s]
  Running the tests in ‘tests/testthat.R’ failed.
  Complete output:
    > library(testthat)
    > library(moderndive)
    >
    > test_check("moderndive")
    [ FAIL 1 | WARN 3 | SKIP 4 | PASS 35 ]

    ══ Skipped tests ═══════════════════════════════════════════════════════════════
    • On CRAN (4)

    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Failure ('test-get_regression_functions.R:100'): README code works ──────────
    `get_regression_points(mpg_mlr_model2, newdata = newcars)` did not produce any warnings.

    [ FAIL 1 | WARN 3 | SKIP 4 | PASS 35 ]
    Error: Test failures
    Execution halted
```

The `get_regression_points` code calls some broom code that used to unduly warn, [as you pointed out in a previous broom issue](https://github.com/tidymodels/broom/issues/896) and in https://github.com/moderndive/moderndive/issues/90. The git history is a bit convoluted there, but we revisited this recently and addressed that warning [as a side effect for another fix](https://github.com/tidymodels/broom/commit/a7d6df53aaf7b95d8949647c75a3a68a506209ca).

A PR coming in a moment to check for this warning conditionally on broom version.🙂 Would you be open to merge and resubmit a moderndive version ahead of our release?

**Comment by rudeboybert** [comment]
Thanks for the heads up! Sure, I'll update on CRAN in the next few days

**Comment by rudeboybert** [comment]
@simonpcouch currently we've set `broom (>= 0.4.3)` in the `DESCRIPTION`. Should we update that to `broom (>= 1.0.0)` given that the next release is `1.0.1`?

**Comment by simonpcouch** [comment]
Awesome, thank you! The next broom version will be 1.0.2. I'd say no need to bump the needed version in DESCRIPTION ahead of your coming release.

Setting `broom (>= 1.0.2)` in DESCRIPTION (and removing the conditionals in #129) in the moderndive release following the coming one will ensure that users never see that warning—those changes would need to wait until after broom 1.0.2 is on CRAN, though. :)
