### ISSUE TITLE
Is there a problem with geom_parallel_slopes?

### ISSUE THREAD

**Issue by rdstern** [moderndive/moderndive#132]
I really welcome this facility and have been teaching the idea for a long time, without the benefit of the ease of fitting the model.

I often use 2 examples to illustrate the importance.  The first is a simple survey on rice yields.  There are different levels of fertiliser and also 3 different varieties.

![image](https://github.com/moderndive/moderndive/assets/11226469/b6970aab-8665-487d-9335-8358608aee4c)

And here are your parallel slopes:

![image](https://github.com/moderndive/moderndive/assets/11226469/90e1a93f-e585-4d44-9cd2-b88e781f54aa)

The interpretation is also of practical importance, namely if this parallel-lines model is adequate, then suggestions on fertilizer can be made separately from those on which variety to use.

The code was:

`last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=fert, y=yield, colour=variety)) + ggplot2::geom_point() + moderndive::geom_parallel_slopes() + theme_grey()
`
That's all fine.  However, if I include facets, so change the code to:

`last_graph <- ggplot2::ggplot(data=survey, mapping=ggplot2::aes(x=fert, y=yield, colour=variety)) + ggplot2::geom_point() + moderndive::geom_parallel_slopes() + theme_grey() + ggplot2::scale_fill_distiller(palette="Blues") + ggplot2::facet_wrap(facets= ~ variety, dir="h")`

Then the graph is as follows:

![image](https://github.com/moderndive/moderndive/assets/11226469/c959b61a-bb57-4485-811f-dbf5d3e70bbc)

So, from the code, it still appears to fit the parallel lines, but they are no longer parallel.  These are just the separate regression lines.  You can see this particularly for the NEW variety, where there isn't much data, so the confidence limits are a lot wider.

I may be doing something wrong here?  If not, is there a problem in your code, when there are facets?

A second example is with climatic data, where we work a lot with different Met services.  Here are the results from Dodoma in Tanzania:

![image](https://github.com/moderndive/moderndive/assets/11226469/79f606e0-c242-48c9-82c0-12e934598041)

The code was as follows:

`last_graph <- ggplot2::ggplot(data=dodoma_by_year_month, mapping=ggplot2::aes(x=year, y=mean_tmin, colour=month_abbr)) + ggplot2::geom_line() + moderndive::geom_parallel_slopes() + theme_grey() + ggplot2::scale_fill_distiller(palette="Blues") + ggplot2::facet_wrap(facets= ~ month_abbr, dir="h")`

Here, the parallel lines are important, because they indicate no seasonal differences in the temperature trends.  Again, the graphs look fine above, but the lines are not parallel.  In this case, the single plot, when the lines are clearly parallel, is not sensible, because the plot is just too cluttered - and I really like facets too.

Happy New Year.

Roger

**Comment by rudeboybert** [comment]
Hi Roger, thanks for posting this. We can look into this. I'm tagging @echasnovski who wrote this function, however I'm not entirely sure how responsive he can be these days.

**Comment by rdstern** [comment]
Hi Albert,  many thanks.  

We have looked further, and I can now be a bit more specific in my request.  When we run simply with the code shown above, it does give a warning that says it does not recognise the `group`, so it defaults to not-parallel lines.  So we tried adding the groups option to the command.  We never succeeded.  Also there is just one factor here, so it is obvious (at least to me) that the slopes should remain parallel for the different facets.  So, if groups needs to be added, then the function could perhaps add them itself?

With more than one factor we can have facets with parallel lines for the factor, within each facet.  But how do we give the group option, so we  have the lines parallel between facets?

It is easy to do this the blood-thirsty way, namely fit the model with no interactions, and then plot the fitted lines.  That works identically whether you use facets or not, so I was surprised, with the distinction between facets and no facets here.

**Comment by echasnovski** [comment]
> Hi Roger, thanks for posting this. We can look into this. I'm tagging @echasnovski who wrote this function, however I'm not entirely sure how responsive he can be these days.

It's been a while since I've looked at this code (and at R in general, to be honest). But I think I am fairly certain that everything here works as intended.

The `geom_parallel_slopes()` is a [somewhat thin wrapper for `geom_smooth()`](https://github.com/moderndive/moderndive/blob/90ab0ddc8ba2a777cbc0809174558184c6b62b9b/R/geom_parallel_slopes.R#L86) in which formula is created in a certain pre-defined way to have parallel slopes.

The thing with faceting, though, is that it intrinsically splits data before applying any other geoms inside of it. So applying `geom_parallel_slopes()` in combination with `facet_wrap()` fits three "parallel slopes" models for each facet which happen to have only single grouping values inside each of them. This is the same logic as in `geom_smooth()`.

The recommended approach here would indeed be to pre-compute fitted lines and plot them separately. Here is an artificial example with `mtcars` (regression of `mpg` based on `hp` and grouped by `gear` assuming same slopes):

```r
library(ggplot2)
library(dplyr)
library(broom)

data <- mtcars %>%
  mutate(gear = as.factor(gear)) %>%
  lm(formula = mpg ~ hp + gear, data = .) %>%
  augment()

ggplot(data, aes(x = hp)) +
  geom_point(aes(y = mpg)) +
  geom_line(aes(y = .fitted)) +
  facet_wrap(~ gear)
```
