### ISSUE TITLE
Passing newdata argument to broom::augment() in moderndive::get_regression_points()

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/moderndive#14]
Not an urgent priority. See line 122-142 of [`R/regression_functions.R`](https://github.com/moderndive/moderndive/blob/master/R/regression_functions.R). Is it worth considering if there is a cleaner way to do this?

**Comment by ismayc** [comment]
Not sure. Seems like this is fine. Can you provide an example of this working in the README so that we can get the test coverage back to 100%?

**Comment by rudeboybert** [comment]
done
