### ISSUE TITLE
Change conf_low and conf_high

### ISSUE THREAD

**Issue by ismayc** [moderndive/moderndive#18]
`conf_low` and `conf_high` seem like strange names from {broom}. Renaming the columns to be `lower_ci` and `upper_ci` seems more consistent with the literature.

**Comment by rudeboybert** [comment]
Makes sense. `conf_low` and `conf_high` are indeed just the `broom` defaults that originate from `base::confint()`

**Comment by rudeboybert** [comment]
Fixed by #22
