### ISSUE TITLE
Switch to using {glue} package instead of {assertive}

### ISSUE THREAD

**Issue by ismayc** [moderndive/moderndive#30]
The {dplyr} package has [some suggestions](
https://github.com/tidyverse/dplyr/blob/d3ded01ac854cbc847afcb1434f49118cea852e8/R/error.R#L48) on how to do this. Should reduce package dependencies in volume quite a bit.

**Comment by rudeboybert** [comment]
No longer need since we removed dependency on `assertive` in #34
