### ISSUE TITLE
get_regression_table not showing all terms of an interaction model

### ISSUE THREAD

**Issue by karoth** [moderndive/moderndive#85]
The model of one categorical and one quantitiative variable has the interaction when you look at the summary(model name) command but not when you look at get_regression_table(model name) I can provide the data and code if desired.

**Comment by rudeboybert** [comment]
Hi @karoth, sorry for the delay. Could you post a reprex (reproducible example)? That will help contextualize this discussion.

**Comment by rudeboybert** [comment]
Hi @karoth, do you happen to have a reprex handy? I'm updating moderndive on CRAN in the next few days
