### ISSUE TITLE
get_regression_points not working with variable names with spaces

### ISSUE THREAD

**Issue by karoth** [moderndive/moderndive#86]
The get_regression_table works fine, but the get_regression_points of the model throws an error about not able to subset the data and it appears to be because the variables are things like `Calories per serving`. I can get code and data if desired.

**Comment by rudeboybert** [comment]
Hey @karoth, thanks for filing this. You do bring to light an implicit assumption for all the `get_regression_X` functions: that all variable names don't have spaces. We chose to do things this way throughout the book b/c beginners always get tripped up by having to use the ` tick marks in such cases. 

Have you heard of the `clean_names()` function from the `janitor` package? It takes in a data frame with "messy" variable names and cleans them up. Check it out:

``` r
library(tidyverse)
library(janitor)
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test

example <- tibble(
  `variable name with spaces` = c(1, 2, 3),
  `total%` = c(4, 5, 6)
)
example
#> # A tibble: 3 x 2
#>   `variable name with spaces` `total%`
#>                         <dbl>    <dbl>
#> 1                           1        4
#> 2                           2        5
#> 3                           3        6

# clean variables names using janitor::clean_names()
example %>% 
  clean_names()
#> # A tibble: 3 x 2
#>   variable_name_with_spaces total_percent
#>                       <dbl>         <dbl>
#> 1                         1             4
#> 2                         2             5
#> 3                         3             6
```

<sup>Created on 2020-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

1. On the one hand we could just include this cleaning function step in all three `get_regression_X` functions, but I'm a bit loathe to make changes to people's data for them.
1. The other thing we could do is keep the functionality as is, but include a warning message that `all variable names should not have spaces in them` whenever the user tries to use such a data frame.

To help me decide, could you let me know which of the two above options sounds better from the user's end?

**Comment by rudeboybert** [comment]
Hey @karoth, do you have any outstanding thoughts on this? I'm inclined to follow the path of least resistance option, especially since generally speaking having variable names with spaces is dicey practice in R
