### ISSUE TITLE
Fix CRAN error by 7/20

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/moderndive#87]
https://cran.r-project.org/web/checks/check_results_moderndive.html

Has to do with update to openintro package

**Comment by simonpcouch** [comment]
Hey there! Just wanted to clarify the link above—the current main branch on this repo is good to go with the 0.7.0 release of broom, but fails with the current moderndive version on CRAN. Won't open a new issue re: your submission timeline since it looks like you'll be making some updates soon. :-)

**Comment by rudeboybert** [comment]
Thanks for the heads up @simonpcouch! Hope all is well in PDX
