### ISSUE TITLE
Add newdata argument to get_regression_points()

### ISSUE THREAD

**Issue by rudeboybert** [moderndive/moderndive#9]
Since `broom::augment(lm_object, newdata = df)` returns fitted/predicted y's for a new data frame `df`, so also should `moderndive::get_regression_points()` allow for a `newdata = df` argument.

**Comment by ismayc** [comment]
Should just be able to add in `...` to the function arguments on this hopefully.

**Comment by rudeboybert** [comment]
yeah, this should be easy; just leaving a reminder to do this for next version.

**Comment by rudeboybert** [comment]
Resolved with 8843467f387b4b88b553e57903deb780e72ad197
