### ISSUE TITLE
Convert {testthat} tests over to Edition 3

### ISSUE THREAD

**Issue by ismayc** [moderndive/moderndive#97]
https://rstudio.com/resources/webinars/testthat-3/. {testthat} is scheduled to go to CRAN in October or November 2020.

**Comment by rudeboybert** [comment]
#100 seems to working just fine with `testthat` 3.0.1 locally, is there an action item here?

**Comment by ismayc** [comment]
"You must deliberately choose to use the 3rd edition, which allows us to make breaking changes without breaking old packages."

**Comment by ismayc** [comment]
Probably fine to just close this, but I’d suspect down the road the changes might be breaking and it might have been good to get ahead of that here.
